INSERT INTO MOVIE(ID, MOVIE_NAME, MOVIE_TYPE, MOVIE_DURATION, HERO_NAME, HEROIN_NAME)
VALUES(1, 'MANAM', 'FAMILY', '2.32HRS', 'NAJARJUNA', 'SHREYA');
INSERT INTO MOVIE(ID, MOVIE_NAME, MOVIE_TYPE, MOVIE_DURATION, HERO_NAME, HEROIN_NAME)
VALUES (2, 'BUNNY', 'THRILLER', '2.40HRS', 'SUNDHAR', 'KAJAL');
INSERT INTO MOVIE(ID, MOVIE_NAME, MOVIE_TYPE, MOVIE_DURATION, HERO_NAME, HEROIN_NAME)
VALUES (3, 'KUSHI', 'LOVE', '2.50HRS', 'PAVAN', 'SAMANTHA');